allow automated prettier formatting check workflow to work on external fork pr

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -1,24 +1,44 @@
 name: Dyvix Quality check
 on:
   pull_request:
-    branches: [main]
 permissions:
   contents: read
   pull-requests: write
+
 jobs:
   format:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v5
       - uses: actions/setup-node@v4
         with:
           node-version: '24'
-      - name: Install dependencies
-        run: npm ci
-      - name: Check formatting
-        run: npx prettier --write . --ignore-path .gitignore
-      - name: Suggest Changes
-        uses: parkerbxyz/suggest-changes@v3
+      - name: Format
+        id: format
+        run: npx prettier@latest --write . --ignore-path .gitignore
+      - name: Check for formatting changes
+        id: diff
+        run: |
+          if git diff --quiet; then
+            echo "changed=false" >> "$GITHUB_OUTPUT"
+          else
+            echo "changed=true" >> "$GITHUB_OUTPUT"
+          fi
+      - name: Generate token
+        id: generate-token
+        uses: actions/create-github-app-token@v2
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+          app-id: ${{ vars.APP_ID }}
+          private-key: ${{ secrets.APP_PRIVATE_KEY }}
+
+      - uses: parkerbxyz/suggest-changes@v3
+        if: steps.diff.outputs.changed == 'true'
+        with:
+          token: ${{ steps.generate-token.outputs.token }}
           comment: 'Prettier found some formatting issues! Click below to apply the fixes directly.'
+          event: 'REQUEST_CHANGES'
+      - name: Fail if something is required
+        if: steps.diff.outputs.changed == 'true'
+        run: |
+          echo "Formatting changes are required."
+          exit 1
